### ISSUE TITLE
Missing methods

### ISSUE THREAD

**Issue by hardcoded** [maxcabourg/graphJava#4]
In my opinion, your Graph interface is missing a lot of methods.
Indeed I think you need more than just methods to add vertices and edges to make a graph.

**Comment by maxcabourg** [comment]
It's okay I'll add some functions

**Comment by hardcoded** [comment]
Please don't forget to close solved issues

2016-04-05 17:15 GMT+02:00 Max Cabourg notifications@github.com:

**Comment by hardcoded** [comment]
[Issue #4] Closing issue
