### ISSUE TITLE
Getters misplaced

### ISSUE THREAD

**Issue by hardcoded** [maxcabourg/graphJava#6]
The getters for vertices should be in the Edge abstract class so that you don't have to cast in either DirectedEdge or UndirectedEdge when you want to access them

**Comment by unrealprojet** [comment]
In the last version of .jar : Edge have 2 methods getV2() and getV1()

V1 is the starting point and V2 the destination if it is a DirectedEdge

**Comment by hardcoded** [comment]
[Issue #6] Closing issue
